apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tomato-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/{username}/tomato
          env:
            - name: TARGET
              value: "tomato"
